CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "FullName" text NOT NULL,
        "Avatar" bytea,
        "PrivateRole" text NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE TABLE "Courses" (
        "Id" uuid NOT NULL,
        "CourseCode" text NOT NULL,
        "Name" text NOT NULL,
        "Symbol" text NOT NULL,
        "Description" text NOT NULL,
        "Photo" bytea,
        CONSTRAINT "PK_Courses" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE TABLE "Glossaries" (
        "Id" uuid NOT NULL,
        "GlossaryCode" text NOT NULL,
        "Sign" text NOT NULL,
        "Description" text NOT NULL,
        "Url" text,
        "Photo" bytea,
        "Category" integer NOT NULL,
        CONSTRAINT "PK_Glossaries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE TABLE "Enrollments" (
        "Id" uuid NOT NULL,
        "EnrollmentCode" text NOT NULL,
        "Timestamp" timestamp with time zone NOT NULL,
        "Status" integer NOT NULL,
        "ProgressPercentage" integer NOT NULL,
        "CourseId" uuid NOT NULL,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_Enrollments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Enrollments_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Enrollments_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES "Courses" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE TABLE "Lessons" (
        "Id" uuid NOT NULL,
        "LessonCode" text NOT NULL,
        "Name" text NOT NULL,
        "Completed" boolean NOT NULL,
        "Url" text NOT NULL,
        "Content" text NOT NULL,
        "CourseId" uuid NOT NULL,
        CONSTRAINT "PK_Lessons" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Lessons_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES "Courses" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE TABLE "LessonGlossaries" (
        "GlossariesId" uuid NOT NULL,
        "LessonsId" uuid NOT NULL,
        CONSTRAINT "PK_LessonGlossaries" PRIMARY KEY ("GlossariesId", "LessonsId"),
        CONSTRAINT "FK_LessonGlossaries_Glossaries_GlossariesId" FOREIGN KEY ("GlossariesId") REFERENCES "Glossaries" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_LessonGlossaries_Lessons_LessonsId" FOREIGN KEY ("LessonsId") REFERENCES "Lessons" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('171a2ef5-43b2-48e2-aeef-463d140ce34c', NULL, 'Admin', 'ADMIN');
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('dda342e0-4705-4b68-8728-59a67e461794', NULL, 'Default', 'DEFAULT');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE INDEX "IX_Enrollments_CourseId" ON "Enrollments" ("CourseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE UNIQUE INDEX "IX_Enrollments_UserId_CourseId" ON "Enrollments" ("UserId", "CourseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE INDEX "IX_LessonGlossaries_LessonsId" ON "LessonGlossaries" ("LessonsId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    CREATE INDEX "IX_Lessons_CourseId" ON "Lessons" ("CourseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251026165103_InitialMigration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251026165103_InitialMigration', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    DROP TABLE "LessonGlossaries";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    DROP TABLE "Glossaries";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    DELETE FROM "AspNetRoles"
    WHERE "Id" = '171a2ef5-43b2-48e2-aeef-463d140ce34c';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    DELETE FROM "AspNetRoles"
    WHERE "Id" = 'dda342e0-4705-4b68-8728-59a67e461794';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    ALTER TABLE "Enrollments" RENAME COLUMN "Timestamp" TO "UpdatedAt";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    ALTER TABLE "Lessons" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    ALTER TABLE "Lessons" ADD "DeletedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    ALTER TABLE "Lessons" ADD "UpdatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    ALTER TABLE "Enrollments" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    ALTER TABLE "Enrollments" ADD "DeletedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    ALTER TABLE "Courses" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    ALTER TABLE "Courses" ADD "DeletedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    ALTER TABLE "Courses" ADD "UpdatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    ALTER TABLE "AspNetUsers" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    ALTER TABLE "AspNetUsers" ADD "DeletedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    ALTER TABLE "AspNetUsers" ADD "UpdatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    CREATE TABLE "Logs" (
        "Id" uuid NOT NULL,
        "Timestamp" timestamp with time zone NOT NULL,
        "UserId" uuid,
        "SourceIp" text,
        "Action" character varying(50) NOT NULL,
        "Status" character varying(50) NOT NULL,
        "Table" character varying(100),
        "RecordId" uuid,
        "BeforeState" text,
        "AfterState" text,
        "Details" text,
        CONSTRAINT "PK_Logs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    CREATE TABLE "Signs" (
        "Id" uuid NOT NULL,
        "SignCode" text NOT NULL,
        "Name" text NOT NULL,
        "Description" text NOT NULL,
        "Url" text,
        "Photo" bytea,
        "Category" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Signs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    CREATE TABLE "LessonsSigns" (
        "LessonsId" uuid NOT NULL,
        "SignsId" uuid NOT NULL,
        CONSTRAINT "PK_LessonsSigns" PRIMARY KEY ("LessonsId", "SignsId"),
        CONSTRAINT "FK_LessonsSigns_Lessons_LessonsId" FOREIGN KEY ("LessonsId") REFERENCES "Lessons" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_LessonsSigns_Signs_SignsId" FOREIGN KEY ("SignsId") REFERENCES "Signs" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('29737e31-c747-4260-854c-7d4b0526ebe8', NULL, 'Default', 'DEFAULT');
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('5b1c19b5-6033-4d16-ad67-3f872956c23b', NULL, 'Admin', 'ADMIN');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    CREATE INDEX "IX_LessonsSigns_SignsId" ON "LessonsSigns" ("SignsId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122143918_RefactorCreatedUpdatedDeleted') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251122143918_RefactorCreatedUpdatedDeleted', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122145659_RefactorDeletedAt') THEN
    DELETE FROM "AspNetRoles"
    WHERE "Id" = '29737e31-c747-4260-854c-7d4b0526ebe8';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122145659_RefactorDeletedAt') THEN
    DELETE FROM "AspNetRoles"
    WHERE "Id" = '5b1c19b5-6033-4d16-ad67-3f872956c23b';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122145659_RefactorDeletedAt') THEN
    ALTER TABLE "Signs" ALTER COLUMN "DeletedAt" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122145659_RefactorDeletedAt') THEN
    ALTER TABLE "Lessons" ALTER COLUMN "DeletedAt" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122145659_RefactorDeletedAt') THEN
    ALTER TABLE "Enrollments" ALTER COLUMN "DeletedAt" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122145659_RefactorDeletedAt') THEN
    ALTER TABLE "Courses" ALTER COLUMN "DeletedAt" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122145659_RefactorDeletedAt') THEN
    ALTER TABLE "AspNetUsers" ALTER COLUMN "DeletedAt" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122145659_RefactorDeletedAt') THEN
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('0d7120e9-8fad-47e4-98f3-62f055fa9956', NULL, 'Default', 'DEFAULT');
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('7e7b7488-4f67-482c-a528-0c3ae9c939cd', NULL, 'Admin', 'ADMIN');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122145659_RefactorDeletedAt') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251122145659_RefactorDeletedAt', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122211139_AddColumnActiverInUserTable') THEN
    DROP TABLE "Logs";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122211139_AddColumnActiverInUserTable') THEN
    DELETE FROM "AspNetRoles"
    WHERE "Id" = '0d7120e9-8fad-47e4-98f3-62f055fa9956';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122211139_AddColumnActiverInUserTable') THEN
    DELETE FROM "AspNetRoles"
    WHERE "Id" = '7e7b7488-4f67-482c-a528-0c3ae9c939cd';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122211139_AddColumnActiverInUserTable') THEN
    ALTER TABLE "AspNetUsers" ADD "Active" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122211139_AddColumnActiverInUserTable') THEN
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('32ada405-25a2-4100-9219-72f1ff8bec71', NULL, 'Default', 'DEFAULT');
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('93b1b28d-a69f-46bb-8625-8b57d3397391', NULL, 'Admin', 'ADMIN');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122211139_AddColumnActiverInUserTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251122211139_AddColumnActiverInUserTable', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214165306_CreateQuizTable') THEN
    DELETE FROM "AspNetRoles"
    WHERE "Id" = '32ada405-25a2-4100-9219-72f1ff8bec71';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214165306_CreateQuizTable') THEN
    DELETE FROM "AspNetRoles"
    WHERE "Id" = '93b1b28d-a69f-46bb-8625-8b57d3397391';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214165306_CreateQuizTable') THEN
    CREATE TABLE "QuizOptions" (
        "Id" uuid NOT NULL,
        "QuestionId" uuid NOT NULL,
        "OptionText" text NOT NULL,
        "IsCorrect" boolean NOT NULL,
        CONSTRAINT "PK_QuizOptions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214165306_CreateQuizTable') THEN
    CREATE TABLE "QuizQuestions" (
        "Id" uuid NOT NULL,
        "LessonId" uuid NOT NULL,
        "QuestionText" text NOT NULL,
        "Feedback" text NOT NULL,
        CONSTRAINT "PK_QuizQuestions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214165306_CreateQuizTable') THEN
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('73a22cbf-da61-45fc-93a0-e773f63886be', NULL, 'Default', 'DEFAULT');
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('dfbd5c80-4f13-4744-ae1d-8d028e4ae086', NULL, 'Admin', 'ADMIN');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214165306_CreateQuizTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251214165306_CreateQuizTable', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170103_AdicionarRelacoesQuiz') THEN
    DELETE FROM "AspNetRoles"
    WHERE "Id" = '73a22cbf-da61-45fc-93a0-e773f63886be';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170103_AdicionarRelacoesQuiz') THEN
    DELETE FROM "AspNetRoles"
    WHERE "Id" = 'dfbd5c80-4f13-4744-ae1d-8d028e4ae086';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170103_AdicionarRelacoesQuiz') THEN
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('5b077651-f269-4f71-9ef3-721e5d27fb95', NULL, 'Admin', 'ADMIN');
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('87ab8a73-00d0-41ce-ae2d-e009c5df1c63', NULL, 'Default', 'DEFAULT');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170103_AdicionarRelacoesQuiz') THEN
    CREATE INDEX "IX_QuizOptions_QuestionId" ON "QuizOptions" ("QuestionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170103_AdicionarRelacoesQuiz') THEN
    ALTER TABLE "QuizOptions" ADD CONSTRAINT "FK_QuizOptions_QuizQuestions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "QuizQuestions" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170103_AdicionarRelacoesQuiz') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251214170103_AdicionarRelacoesQuiz', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170601_AdicionarRelacaoLessonQuizQuestions') THEN
    DELETE FROM "AspNetRoles"
    WHERE "Id" = '5b077651-f269-4f71-9ef3-721e5d27fb95';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170601_AdicionarRelacaoLessonQuizQuestions') THEN
    DELETE FROM "AspNetRoles"
    WHERE "Id" = '87ab8a73-00d0-41ce-ae2d-e009c5df1c63';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170601_AdicionarRelacaoLessonQuizQuestions') THEN
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('21d3b5a6-58aa-4341-afb2-111f5856b03c', NULL, 'Admin', 'ADMIN');
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('a70cbba4-15cd-4b1e-ab52-a05b962b6ae3', NULL, 'Default', 'DEFAULT');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170601_AdicionarRelacaoLessonQuizQuestions') THEN
    CREATE INDEX "IX_QuizQuestions_LessonId" ON "QuizQuestions" ("LessonId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170601_AdicionarRelacaoLessonQuizQuestions') THEN
    ALTER TABLE "QuizQuestions" ADD CONSTRAINT "FK_QuizQuestions_Lessons_LessonId" FOREIGN KEY ("LessonId") REFERENCES "Lessons" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170601_AdicionarRelacaoLessonQuizQuestions') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251214170601_AdicionarRelacaoLessonQuizQuestions', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170717_AdicionandoCreatedUpdatedDeleted') THEN
    DELETE FROM "AspNetRoles"
    WHERE "Id" = '21d3b5a6-58aa-4341-afb2-111f5856b03c';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170717_AdicionandoCreatedUpdatedDeleted') THEN
    DELETE FROM "AspNetRoles"
    WHERE "Id" = 'a70cbba4-15cd-4b1e-ab52-a05b962b6ae3';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170717_AdicionandoCreatedUpdatedDeleted') THEN
    ALTER TABLE "QuizQuestions" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170717_AdicionandoCreatedUpdatedDeleted') THEN
    ALTER TABLE "QuizQuestions" ADD "DeletedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170717_AdicionandoCreatedUpdatedDeleted') THEN
    ALTER TABLE "QuizQuestions" ADD "UpdatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170717_AdicionandoCreatedUpdatedDeleted') THEN
    ALTER TABLE "QuizOptions" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170717_AdicionandoCreatedUpdatedDeleted') THEN
    ALTER TABLE "QuizOptions" ADD "DeletedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170717_AdicionandoCreatedUpdatedDeleted') THEN
    ALTER TABLE "QuizOptions" ADD "UpdatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170717_AdicionandoCreatedUpdatedDeleted') THEN
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('937cc5fc-b907-4d1f-bd4f-d9dd21d8ff08', NULL, 'Admin', 'ADMIN');
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('acd97763-cf0d-4593-984f-a7891d5fc0af', NULL, 'Default', 'DEFAULT');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214170717_AdicionandoCreatedUpdatedDeleted') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251214170717_AdicionandoCreatedUpdatedDeleted', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260206012733_LessonTopics') THEN
    DELETE FROM "AspNetRoles"
    WHERE "Id" = '937cc5fc-b907-4d1f-bd4f-d9dd21d8ff08';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260206012733_LessonTopics') THEN
    DELETE FROM "AspNetRoles"
    WHERE "Id" = 'acd97763-cf0d-4593-984f-a7891d5fc0af';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260206012733_LessonTopics') THEN
    CREATE TABLE "LessonTopic" (
        "Id" uuid NOT NULL,
        "Order" integer NOT NULL,
        "Title" text NOT NULL,
        "TextContent" text NOT NULL,
        "LessonId" uuid NOT NULL,
        CONSTRAINT "PK_LessonTopic" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LessonTopic_Lessons_LessonId" FOREIGN KEY ("LessonId") REFERENCES "Lessons" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260206012733_LessonTopics') THEN
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('2cfa1f13-8c4c-4304-9d21-9c49fe8d177a', NULL, 'Admin', 'ADMIN');
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('9c23c72b-348b-4511-99a0-424a1538643d', NULL, 'Default', 'DEFAULT');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260206012733_LessonTopics') THEN
    CREATE INDEX "IX_LessonTopic_LessonId" ON "LessonTopic" ("LessonId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260206012733_LessonTopics') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260206012733_LessonTopics', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260210001018_AddOrderToLesson') THEN
    DELETE FROM "AspNetRoles"
    WHERE "Id" = '2cfa1f13-8c4c-4304-9d21-9c49fe8d177a';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260210001018_AddOrderToLesson') THEN
    DELETE FROM "AspNetRoles"
    WHERE "Id" = '9c23c72b-348b-4511-99a0-424a1538643d';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260210001018_AddOrderToLesson') THEN
    ALTER TABLE "Lessons" ADD "Order" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260210001018_AddOrderToLesson') THEN
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('a6cd61b0-14da-4023-89ab-73f71f815da9', NULL, 'Admin', 'ADMIN');
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('d22d4470-dde9-443d-9fb8-ad812b042607', NULL, 'Default', 'DEFAULT');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260210001018_AddOrderToLesson') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260210001018_AddOrderToLesson', '8.0.20');
    END IF;
END $EF$;
COMMIT;

